"""add age column

Revision ID: f6d4c20ae59b
Revises: 4913525af2d6
Create Date: 2026-06-21 21:54:38.104743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d4c20ae59b'
down_revision: Union[str, Sequence[str], None] = '4913525af2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False), schema='advance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age', schema='advance')
    # ### end Alembic commands ###
